### ISSUE TITLE
spring.datasource.init-sql doesn't get executed because it isn't supported

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud-stream-app-starters/jdbc#1]
According to  readme in `source.jdbc`, there is  `spring.datasource.init-sql` property  that, as I understand, should be executed on startup, but it is not happening.
I also can't find the mapping for this property in [DataSourceProperties](https://github.com/spring-projects/spring-boot/tree/v1.4.2.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/DataSourceProperties.java)

**Comment by artembilan** [comment]
Yeah, confirmed.

I don't know how, but there is really no `spring.datasource.init-sql` property.
You should use `spring.datasource.schema` and `spring.datasource.data` properties for scripts.

They works by default though, if the first one is in the root of classpath with the `schema.sql` name and the second one with the `data.sql` name. The property `spring.datasource.initialize` is `true` by default.

The README will be fixed.

Thank you for catching that out!

**Comment by jvmlet** [comment]
BTW,  sink suffers from the same issue.
