### ISSUE TITLE
Issue with the jar built from latest code

### ISSUE THREAD

**Issue by hafizca** [spring-cloud-stream-app-starters/jdbc#13]
Getting below error:

no main manifest attribute, in spring-cloud-starter-stream-source-jdbc-1.1.2.BUILD-SNAPSHOT.jar

**Comment by artembilan** [comment]
How do you build, please?

**Comment by hafizca** [comment]
sorry.. but build worked using maven.. i used mvn clean install..  but its not the uber jar which i get .. also , i get the error "no main manifest attribute, in spring-cloud-starter-stream-source-jdbc-1.1.2.BUILD-SNAPSHOT.jar"  if i use the jar built from this source code..

**Comment by artembilan** [comment]
These kind of projects isn't intended to be build from the IDE. They are called "starters" and there is specific maven plugin to build the target application with selected binder: http://docs.spring.io/spring-cloud-stream-app-starters/docs/Bacon.M1/reference/html/_introduction.html#_building_the_artifacts.

So, 
```
mvn clean install -PgenerateApps
```
and you will have all the binder-based artifacts in the `/app` directory. And yes, already they will be uber jars - ready for the run Boot applications!

**Comment by sabbyanandan** [comment]
Hi, @hafizca: Please follow the instructions posted by @artembilan above. If you have any other questions, please consider opening a new thread in [StackOverflow](http://stackoverflow.com/questions/tagged/spring-cloud-dataflow) going forward.
