### ISSUE TITLE
Exception while trying to deserialize String in Column Expression

### ISSUE THREAD

**Issue by usopan** [spring-cloud-stream-app-starters/jdbc#22]
```
Could not find value for column 'a': EL1021E: A problem occurred whilst attempting to access the property 'a': 'Exception while trying to deserialize String'
```
I have set following properties in deployment
```
app.test-sink.spring.cloud.stream.consumer.contentType=application/json
app.test-sink.spring.cloud.stream.bindings.input.consumer.headerMode=raw
app.test-sink.spring.cloud.stream.kafka.bindings.input.consumer.resetOffsets=true
app.test-sink.spring.cloud.stream.kafka.bindings.input.consumer.startOffset=earliest
app.test-sink.spring.cloud.stream.default.contentType=text/plain
app.test-sink.spring.cloud.stream.bindings.input.consumer.configuration.value.deserializer=class org.apache.kafka.common.serialization.StringSerializer
app.test-sink.spring.cloud.stream.bindings.input.consumer.configuration.key.deserializer=class org.apache.kafka.common.serialization.StringSerializer
app.test-sink.spring.cloud.stream.bindings.input.consumer.configuration.value.serializer=class org.apache.kafka.common.serialization.StringSerializer
app.test-sink.spring.cloud.stream.bindings.input.consumer.configuration.key.serializer=class org.apache.kafka.common.serialization.StringSerializer
app.test-sink.spring.cloud.stream.bindings.input.consumer.useNativeEncoding=true
```

**Comment by artembilan** [comment]
I wonder if your problem is related to the #16 .

On the other hand not enough info in your subject to let us to reproduce.

Any chances to have a simple configuration what you try to do with this... With what? `Source` or `Sink` problem?

Would be also great just to have like a Pull Request with the test for your use-case to play from our side.

Thanks for understanding.

**Comment by usopan** [comment]
Let me do some more testing and come up with more information.
But broadly speaking, I am trying to persist data into mysql using jdbc-sink, I am providing column mapping with following string  
--columns=orderlineid:id,orderdate:orderDate

both of these fields are present in payload at the root level, I am wondering if this has something to do with contentType property, or If I am passing the content type property with correct context.

**Comment by sabbyanandan** [comment]
@usopan: Any updates? Also, are you on `master`?

**Comment by usopan** [comment]
I was able to move ahead by setting content-type for input and output consumer and No I was not on master.
I was on an older version and property names were probably different.
