### ISSUE TITLE
jdbc sink always making 10 connection maximum with MySQL Database

### ISSUE THREAD

**Issue by suresh-chidham** [spring-cloud-stream-app-starters/jdbc#29]
1) Is 10 connections are Max connections made by SCDF JDBC sink or its a default settings to JDBC sink ?

2) JDBC sink makes live connections to MySQL DB even without any dataflow happening to the stream. So can we set any properties of JDBC sink to reduce the connection period to MySQL if no data flows. or release the connections if no data input to JDBC sink.

Due to unavailable connections, we are getting too many connection issue with MySQL DB. 

Please advice us any jdbc sink properties, we can configure to resolve  above issue in jdbc sink.

**Comment by artembilan** [comment]
The sink is fully based on the auto-configured by Spring Boot a `DataSource` bean. And by default it uses a HikariCP.
So, to tweak the connection poll you need to consult with their docs. I found some sample here: https://www.baeldung.com/spring-boot-hikari

**Comment by suresh-chidham** [comment]
Thanks for clarifying which CP  used in JDBC sink spring boot app.  I have used HikariCP connection properties in my stream.  Its working fine.  I dont get too many connection.
