### ISSUE TITLE
Oracle DB driver support for JDBC source 

### ISSUE THREAD

**Issue by respondsid** [spring-cloud-stream-app-starters/jdbc#52]
I am trying to use this source for a oracle database, from dependencies it doesnt look like the oracle drivers are supported.

**Comment by sobychacko** [comment]
@respondsid Oracle drivers are not included by default. You have to do it on your own. 
You can follow the patching procedures [here](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Einstein.SR6/reference/htmlsingle/#_patching_pre_built_applications).
You can also clone this repo and then regenerate the apps if you choose to go that way.

**Comment by sabbyanandan** [comment]
Hi, @respondsid. We attempt to package only the open-source and license-friendly drivers by default. To use Oracle, however, you'd have to have a valid license from Oracle, and for the same reason, we don't bundle the Oracle driver by default  — we cannot redistribute unlicensed software. 

You can add it to the app and build it yourself, though.

**Comment by respondsid** [comment]
Makes sense appreciate the quick response
